version: '3.2'

services:

#================================================================================================
# CORE-BASE
#================================================================================================
  base:
    image: dockerframework/core-base:3.6
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - TERM=xterm
      #- CONTAINER_HOST=                          # container host (defaut: hostname of the container)
      #- CONTAINER_RESOLVER=route                 # IP resolver method for container (disable/route/interface, default: route)
      #- CONTAINER_RESOLVER_INTERFACENAME=eth0    # network interface name for IP resolver (default: eth0)
      #- CONTAINER_RESOLVER_INTERFACETYPE=inet    # network interface type for IP resolver (inet/inet6, default: inet)
